# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MNIST' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MNIST
    pod 'TensorFlowLiteSwift/CoreML', '~> 2.4.0'
  target 'MNISTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MNISTUITests' do
    # Pods for testing
  end

end
